### ISSUE TITLE
Cannot use WindowBuilder in stable (rev29) or edge (rev38)

### ISSUE THREAD

**Issue by lwbt** [snapcrafters/eclipse#12]
I tried creating a project using WindowBuilder on Ubuntu 18.04, I installed the respective packages through the IDE. When trying to open the design view I got the following error message on stable:

    Eclipse is running under 0, but this Java project has a 10 Java compliance level, so WindowBuilder will not be able to load classes from this project. Use a lower level of Java for the project, or run Eclipse using a newer Java version.

I got different error on edge but both seem to be rooted in the snap packaging from what I can tell after trying for over 1-3 hours to understand and work around the problem.

**Comment by ThyMYthOS** [comment]
@lwbt packaging changed for 2019.03, can you try again?

**Comment by lwbt** [comment]
I tried again (had to remember what the project was about and troubleshoot some issues).

It works now! Thanks.
