### ISSUE TITLE
No launcher entry since revision 41

### ISSUE THREAD

**Issue by ThyMYthOS** [snapcrafters/eclipse#17]
The KDE launcher menu does not show an entry for snapped eclipse anymore. Might be related to ac8088bdb8a2272ff6032b7f7b1d19878772c0b7.

```
# find /snap/eclipse -name "eclipse.desktop"
/snap/eclipse/40/eclipse.desktop
/snap/eclipse/40/meta/gui/eclipse.desktop
/snap/eclipse/41/meta/gui/eclipse.desktop
```

**Comment by popey** [comment]
Thanks @ThyMYthOS !
I'm going to propose a PR which fixes this by modifying the desktop file, rather than revert the changes. I do appreciate the effort though, thanks.
