### ISSUE TITLE
Eclipse Photon R (4.8.0) Released

### ISSUE THREAD

**Issue by alculete** [snapcrafters/eclipse#2]
Eclipse photon [released](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/photon/R/eclipse-jee-photon-R-linux-gtk-x86_64.tar.gz)

**Comment by popey** [comment]
Build can be monitored at https://build.snapcraft.io/user/snapcrafters/eclipse

**Comment by popey** [comment]
This is now in the candidate channel. Thanks for the issue report @alculete, it's very much appreciated!
