### ISSUE TITLE
Opening eclipse causes GNOME to freeze.

### ISSUE THREAD

**Issue by mystiquewolf** [snapcrafters/eclipse#22]
Mouse can be moved, but nothing responds to hover/click. From different console htop does not show high RAM or CPU usage, i have no idea what the problem might be caused by.

**Comment by mystiquewolf** [comment]
Ubuntu 19.10, GNOME 3.34.1

**Comment by merlijn-sebrechts** [comment]
Is this issue still present in the latest version?

**Comment by mystiquewolf** [comment]
I don't know. Since then i've switched to KDE and i don't use both Eclipse and GNOME anymore.

**Comment by merlijn-sebrechts** [comment]
Ok, I can't reproduce this on Ubuntu 22.04, and we've had a bunch of releases since you first reported so I'll close this issue for now.

Thanks for reporting!
