### ISSUE TITLE
eclipse snap fails to find jre

### ISSUE THREAD

**Issue by Mazurs** [snapcrafters/eclipse#25]
On Ubuntu 19.10 when installing eclipse through snaps it fails to run, printing this message:
```
Eclipse:
A Java Runtime Environment (JRE) or Java Development Kit (JDK)
must be available in order to run Eclipse. No Java virtual machine
was found after searching the following locations:
/snap/eclipse/48/jre/bin/java
java in your current PATH
```

**Comment by JohnBlood** [comment]
I just ran into the same issue on Ubuntu Mate. If you guys don't want to package Java in the snap, please put a message on the Snapcraft Store warning that Java needs to be installed before it will run. It would save a lot of confusion.

**Comment by pixelr0** [comment]
same on ubuntu 20.04

~$ eclipse 
Eclipse:
A Java Runtime Environment (JRE) or Java Development Kit (JDK)
must be available in order to run Eclipse. No Java virtual machine
was found after searching the following locations:
/snap/eclipse/48/jre/bin/java
java in your current PATH

**Comment by indianprogrammer** [comment]
same issue here

**Comment by alexhaydock** [comment]
It seems like this issue might be by design, but not well documented on the installation page for the Snap, which would be a good place for it.

This is a `--classic` Snap so it can rely on system-level dependencies, including a system JRE.

There are a few ways to install one, but an easy way is to do:
```
sudo apt install default-jre
```

**Comment by popey** [comment]
I have added mention of installing a jre on the store page for eclipse.
