### ISSUE TITLE
Eclipse doesn't keep user plungins after upgrade

### ISSUE THREAD

**Issue by alculete** [snapcrafters/eclipse#3]
When upgrading to a new version eclipse doesn't keep plugins installed (i.e. JBoss Tools) and old workspace paths. This behavior only happens on the snap version. On deb version, you are able to keep old configuration and plugins

**Comment by awesome-manuel** [comment]
After the first install of the Eclipse snap I have the following files/foldes in `~/.eclipse`:

 360744385_linux_gtk_x86_64
 org.eclipse.epp.logging.aeri
 org.eclipse.oomph.p2
 org.eclipse.oomph.setup
 org.eclipse.platform_4.6.3_676877592_linux_gtk_x86_64

The plugins are in `360744385_linux_gtk_x86_64`. Not sure what the number prefix means.
After the upgrade my .eclipse folder looks like this:

 360744347_linux_gtk_x86_64
 360744385_linux_gtk_x86_64
 org.eclipse.epp.logging.aeri
 org.eclipse.oomph.p2
 org.eclipse.oomph.setup
 org.eclipse.platform_4.6.3_676877592_linux_gtk_x86_64
 org.eclipse.tips.state

The folder `360744347_linux_gtk_x86_64` is new and contains no plugins.

**Comment by brlin-tw** [comment]
Refer [Eclipse CDT - snap - snapcraft.io](https://forum.snapcraft.io/t/eclipse-cdt/5426) for discussion and potential fix of this issue.

**Comment by ThyMYthOS** [comment]
Also have a look at https://github.com/snapcrafters/eclipse/pull/9

**Comment by ThyMYthOS** [comment]
#9 needs a little change. I tried the following and it works for me:
1. Install stable eclipse `snap install --channel=stable --classic eclipse`
2. Start eclipse with `eclipse -configuration /home/mythos/snap/eclipse/current/amd64/configuration`
3. Install some plugins from the Marketplace
4. Install edge eclipse `snap install --channel=edge --classic eclipse`
5. Start eclipse with `eclipse -configuration /home/mythos/snap/eclipse/current/amd64/configuration`
6. Eclipse migrates the plugins

**Comment by ThyMYthOS** [comment]
@popey for me this is fixed by #9
