### ISSUE TITLE
Cannot use lombok because eclipse.ini is read only

### ISSUE THREAD

**Issue by tstephen** [snapcrafters/eclipse#5]
[Project Lombok](https://projectlombok.org/) in case you're unaware of it is a way to avoid writing so much boilerplate code in Java. 

However to use it with Eclipse (or other IDEs) you have to modify the way the IDE starts. Specifically you need the line:

```
-javaagent:/path/to/local/lombok.jar
```
in the eclipse.ini after `-vmargs`. Typically you run the lombok jar which displays a GUI to do this for you to avoid making typos in the ini file with manual editing.

This does not work as the snap file system is read-only (for understandable reasons). I'm only familiar with using snaps not creating them. Is it possible to make the ini file alone editable?

**Comment by ThyMYthOS** [comment]
You can add this as a command line parameter like this:

 `eclipse -javaagent:/path/to/local/lombok.jar`

**Comment by tstephen** [comment]
Ok that's true but the command is executed from the .desktop file which i imagine is read only too. So i need to create and maintain my own desktop file? I _can_ do that but I thought there was a way to expose files from snaps? Nextcloud seems to allow such things from my small use of it

**Comment by ThyMYthOS** [comment]
Fixed by #41

**Comment by lucyllewy** [comment]
Closing as fixed.

**Comment by tstephen** [comment]
Thanks #41 solves this perfectly.
