### ISSUE TITLE
Support user `dropins` directory

### ISSUE THREAD

**Issue by ryanmkurtz** [snapcrafters/eclipse#50]
### What changes would you like?

My project relies on the `dropins` directory to automate the installation of our Eclipse plugin.  Since the one in `/snap/eclipse/dropins` cannot be used (read-only filesystem), I tried creating `~/snap/eclipse/current/<arch>/dropins` and dropped my archive in, but it didn't seem to pick it up.  It would be great if this worked.

**Comment by ThyMYthOS** [comment]
See https://www.ibm.com/support/pages/configuring-additional-eclipse-dropins-directories how to configure extra dropins directories.

**Comment by ryanmkurtz** [comment]
Thank you.  I haven't tried it yet but I assume that will work for me.
